name: eelisa-workshop
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - notebook
  - ipykernel
  - ipython
  - ipywidgets
  - jupyterlab_widgets
  - lxml
  - pandas
  - python-levenshtein
  - pip
  - pip:
      - collatex==2.3
