name: eelisa-workshop

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - notebook
  - jupyterlab
  - ipykernel
  - ipywidgets

  - pandas
  - numpy
  - lxml
  - matplotlib
  - networkx
  - beautifulsoup4

  - r-base=4.3
  - r-irkernel
  - r-tidyverse
  - r-xml2
  - r-stringr
  - r-readr
  - r-dplyr
  - r-tidyr
  - r-purrr
  - r-igraph
  - r-ape
  - r-phangorn
  - r-remotes

  - pip
  - pip:
      - collatex
